### ISSUE TITLE
[Bug]: Carthage parsing failed due to wrong punctuation

### ISSUE THREAD

**Issue by JeremyHuang37** [Cokile/TweaKit#2]
## What did you do?

Installed TweaKit via Carthage

## What did you expect to happen?

Installing TweaKit using Carthage successfully

## What happened instead?

Parse error: expected string after dependency type in line: github 'Alpensegler/TweaKit' ~> 1.0

## Extra information

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/53163315/201954467-a9662af2-32b2-4b9b-8ee3-b8753b301ba9.png">

**Comment by Cokile** [comment]
Nice catch, bro.

**Comment by Cokile** [comment]
Just published 1.0.3 for the fix,  you can use `carthage update TweaKit` to install the update.
