### ISSUE TITLE
Feature request: <tappable action request>

### ISSUE THREAD

**Issue by BayramInanc** [Cokile/TweaKit#5]
## What's you idea or suggestion?

Hi, thanks for your great work. Can you implement tappable tweak. For example when we tap a section, it will open lists of actions, we can choose any of the action by touching and it happens. We can think of it like tappable action .

We can add this as a section and also list of tappable action when tapping a section?

For example : 

Action list section user taps, then 5 actions show 

* do A
* do B
* ..
* ..
* do E

when user touches doA do action will happen, no need to save this to cache or file, only do it and forget.

**Comment by BayramInanc** [comment]
SwiftTweaks library has this feature, in their sample app there is a Actions section. when I tap "Print to console" action, it will print log to xcode console. @Cokile

**Comment by BayramInanc** [comment]
Also if one action should be taken, then you can add directly add tappable action as a section.

**Comment by Cokile** [comment]
Hi @BayramInanc, thanks for the feedback!

That's the difference between SwiftTweaks and TweaKit. From the perspective of TweaKit, a tweak is something whose value can be tweaked(changed) at runtime. Action does not fit in this context. So there is no plan to add support for action(at least for now).

An alternative solution is to write your own DebugVC with a table view, each cell is bound to the action you need and there is a cell to show tweaks.

**Comment by BayramInanc** [comment]
Ha, I get it. Thanks for response @Cokile
